import type { Metadata } from 'next';
import Navbar from '../_components/navbar';
import { SidebarProvider } from '@/components/ui/sidebar';
import DahboardSidebar from '../_components/sidebar';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
         <SidebarProvider>
            <DahboardSidebar />
          <div className='relative min-h-screen w-full flex flex-col'>

            <Navbar />
            {children}
          </div>
         </SidebarProvider>
      </body>
    </html>
  );
}
