import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from 'next-themes';
import StoreProvider from '@/(config)/store/provider';
import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <ThemeProvider defaultTheme="system" enableSystem attribute="class">
             <Toaster />
            {children}
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
