import { OrdersInterface } from "@/utils/types";

export const orders: OrdersInterface[] = [
  {
    id: '1',
    customerName: 'Ahmad Ali',
    email: 'ahmad@example.com',
    product: 'Laptop',
    amount: 85000,
    status: 'completed',
    deliveryStatus: 'delivered',
    date: '2024-12-20',
    orderId: 'ORD-001',
    trackingId: 'TRK-982104',
  },
  {
    id: '2',
    customerName: 'Sara Khan',
    email: 'sara@example.com',
    product: 'Phone',
    amount: 45000,
    status: 'paid',
    deliveryStatus: 'shipped',
    date: '2024-12-21',
    orderId: 'ORD-002',
    trackingId: 'TRK-553210',
  },
  {
    id: '3',
    customerName: 'Hassan Raza',
    email: 'hassan@example.com',
    product: 'Headphones',
    amount: 8500,
    status: 'unpaid',
    deliveryStatus: 'pending',
    date: '2024-12-22',
    orderId: 'ORD-003',
    trackingId: 'not assigned',
  },
  {
    id: '4',
    customerName: 'Ayesha Ahmed',
    email: 'ayesha@example.com',
    product: 'Smartwatch',
    amount: 25000,
    status: 'failed',
    deliveryStatus: 'cancelled',
    date: '2024-12-19',
    orderId: 'ORD-004',
    trackingId: 'not assigned',
  },
  {
    id: '5',
    customerName: 'Bilal Shah',
    email: 'bilal@example.com',
    product: 'Tablet',
    amount: 55000,
    status: 'return',
    deliveryStatus: 'delivered',
    date: '2024-12-18',
    orderId: 'ORD-005',
    trackingId: 'TRK-112233',
  },
  {
    id: '6',
    customerName: 'Fatima Malik',
    email: 'fatima@example.com',
    product: 'Camera',
    amount: 95000,
    status: 'completed',
    deliveryStatus: 'delivered',
    date: '2024-12-23',
    orderId: 'ORD-006',
    trackingId: 'TRK-445566',
  },
  {
    id: '7',
    customerName: 'Usman Tariq',
    email: 'usman@example.com',
    product: 'Keyboard',
    amount: 6500,
    status: 'paid',
    deliveryStatus: 'shipped',
    date: '2024-12-24',
    orderId: 'ORD-007',
    trackingId: 'TRK-778899',
  },
  {
    id: '8',
    customerName: 'Zainab Hussain',
    email: 'zainab@example.com',
    product: 'Mouse',
    amount: 3500,
    status: 'unpaid',
    deliveryStatus: 'pending',
    date: '2024-12-17',
    orderId: 'ORD-008',
    trackingId: 'not assigned',
  },
  {
    id: '9',
    customerName: 'Imran Baig',
    email: 'imran@example.com',
    product: 'Monitor',
    amount: 42000,
    status: 'completed',
    deliveryStatus: 'delivered',
    date: '2024-12-16',
    orderId: 'ORD-009',
    trackingId: 'TRK-334455',
  },
  {
    id: '10',
    customerName: 'Hina Naz',
    email: 'hina@example.com',
    product: 'Speaker',
    amount: 12000,
    status: 'failed',
    deliveryStatus: 'cancelled',
    date: '2024-12-15',
    orderId: 'ORD-010',
    trackingId: 'not assigned',
  },
  {
    id: '11',
    customerName: 'Kashif Iqbal',
    email: 'kashif@example.com',
    product: 'Router',
    amount: 7500,
    status: 'paid',
    deliveryStatus: 'shipped',
    date: '2024-12-14',
    orderId: 'ORD-011',
    trackingId: 'TRK-667788',
  },
  {
    id: '12',
    customerName: 'Mariam Siddique',
    email: 'mariam@example.com',
    product: 'Webcam',
    amount: 9500,
    status: 'return',
    deliveryStatus: 'delivered',
    date: '2024-12-13',
    orderId: 'ORD-012',
    trackingId: 'TRK-223344',
  },
  {
    id: '13',
    customerName: 'Rizwan Ashraf',
    email: 'rizwan@example.com',
    product: 'Hard Drive',
    amount: 15000,
    status: 'completed',
    deliveryStatus: 'delivered',
    date: '2024-12-12',
    orderId: 'ORD-013',
    trackingId: 'TRK-556677',
  },
  {
    id: '14',
    customerName: 'Sana Butt',
    email: 'sana@example.com',
    product: 'SSD',
    amount: 18000,
    status: 'unpaid',
    deliveryStatus: 'pending',
    date: '2024-12-11',
    orderId: 'ORD-014',
    trackingId: 'not assigned',
  },
  {
    id: '15',
    customerName: 'Farhan Yousaf',
    email: 'farhan@example.com',
    product: 'Graphics Card',
    amount: 125000,
    status: 'paid',
    deliveryStatus: 'shipped',
    date: '2024-12-10',
    orderId: 'ORD-015',
    trackingId: 'TRK-889900',
  },
  {
    id: '16',
    customerName: 'Nida Zaheer',
    email: 'nida@example.com',
    product: 'Microphone',
    amount: 11000,
    status: 'failed',
    deliveryStatus: 'cancelled',
    date: '2024-12-09',
    orderId: 'ORD-016',
    trackingId: 'not assigned',
  },
  {
    id: '17',
    customerName: 'Adnan Rauf',
    email: 'adnan@example.com',
    product: 'USB Hub',
    amount: 4500,
    status: 'completed',
    deliveryStatus: 'delivered',
    date: '2024-12-08',
    orderId: 'ORD-017',
    trackingId: 'TRK-101112',
  },
  {
    id: '18',
    customerName: 'Rabia Nasir',
    email: 'rabia@example.com',
    product: 'Power Bank',
    amount: 5500,
    status: 'paid',
    deliveryStatus: 'pending',
    date: '2024-12-07',
    orderId: 'ORD-018',
    trackingId: 'not assigned',
  },
  {
    id: '19',
    customerName: 'Waqas Munir',
    email: 'waqas@example.com',
    product: 'Charger',
    amount: 2500,
    status: 'return',
    deliveryStatus: 'delivered',
    date: '2024-12-06',
    orderId: 'ORD-019',
    trackingId: 'TRK-131415',
  },
  {
    id: '20',
    customerName: 'Amna Saleem',
    email: 'amna@example.com',
    product: 'Cable',
    amount: 1500,
    status: 'unpaid',
    deliveryStatus: 'pending',
    date: '2024-12-05',
    orderId: 'ORD-020',
    trackingId: 'not assigned',
  },
  {
    id: '21',
    customerName: 'Saeed Akhtar',
    email: 'saeed@example.com',
    product: 'Desk Lamp',
    amount: 6000,
    status: 'completed',
    deliveryStatus: 'delivered',
    date: '2024-12-04',
    orderId: 'ORD-021',
    trackingId: 'TRK-161718',
  },
  {
    id: '22',
    customerName: 'Maryam Riaz',
    email: 'maryam@example.com',
    product: 'Chair',
    amount: 35000,
    status: 'failed',
    deliveryStatus: 'cancelled',
    date: '2024-12-03',
    orderId: 'ORD-022',
    trackingId: 'not assigned',
  },
  {
    id: '23',
    customerName: 'Junaid Akram',
    email: 'junaid@example.com',
    product: 'Desk',
    amount: 45000,
    status: 'paid',
    deliveryStatus: 'shipped',
    date: '2024-12-02',
    orderId: 'ORD-023',
    trackingId: 'TRK-192021',
  },
  {
    id: '24',
    customerName: 'Sadia Amin',
    email: 'sadia@example.com',
    product: 'Gaming Chair',
    amount: 55000,
    status: 'completed',
    deliveryStatus: 'delivered',
    date: '2024-12-01',
    orderId: 'ORD-024',
    trackingId: 'TRK-222324',
  },
  {
    id: '25',
    customerName: 'Hamza Javed',
    email: 'hamza@example.com',
    product: 'Cooling Pad',
    amount: 8000,
    status: 'unpaid',
    deliveryStatus: 'pending',
    date: '2024-11-30',
    orderId: 'ORD-025',
    trackingId: 'not assigned',
  },
  {
    id: '26',
    customerName: 'Kiran Afzal',
    email: 'kiran@example.com',
    product: 'Laptop Bag',
    amount: 4000,
    status: 'return',
    deliveryStatus: 'delivered',
    date: '2024-11-29',
    orderId: 'ORD-026',
    trackingId: 'TRK-252627',
  },
  {
    id: '27',
    customerName: 'Aamir Saeed',
    email: 'aamir@example.com',
    product: 'Screen Protector',
    amount: 1200,
    status: 'paid',
    deliveryStatus: 'shipped',
    date: '2024-11-28',
    orderId: 'ORD-027',
    trackingId: 'TRK-282930',
  },
  {
    id: '28',
    customerName: 'Naila Shah',
    email: 'naila@example.com',
    product: 'Phone Case',
    amount: 2000,
    status: 'completed',
    deliveryStatus: 'delivered',
    date: '2024-11-27',
    orderId: 'ORD-028',
    trackingId: 'TRK-313233',
  },
  {
    id: '29',
    customerName: 'Yasir Mahmood',
    email: 'yasir@example.com',
    product: 'Earbuds',
    amount: 15000,
    status: 'failed',
    deliveryStatus: 'cancelled',
    date: '2024-11-26',
    orderId: 'ORD-029',
    trackingId: 'not assigned',
  },
  {
    id: '30',
    customerName: 'Mehwish Ali',
    email: 'mehwish@example.com',
    product: 'Printer',
    amount: 38000,
    status: 'unpaid',
    deliveryStatus: 'pending',
    date: '2024-11-25',
    orderId: 'ORD-030',
    trackingId: 'not assigned',
  },
];